### ISSUE TITLE
feature: Add context menu for sorting the guild list by criteria

### ISSUE THREAD

**Issue by randomzigzag** [sparr/powercord-guild-list-order-shortcuts#1]
Examples for criteria include alphabetically, by join date, by creation date, by member count, etc. (ascending and descending versions)

**Comment by sparr** [comment]
How would you want this to handle existing folders?

**Comment by randomzigzag** [comment]
I'm not sure. I thought of two ways to approach folders:

* Average the dates/member counts
* Ignore folders and place them at the beginning/end

Folders have titles, if I remember correctly.

**Comment by sparr** [comment]
Easy option is to ignore them, so maybe I'll do that first. Options for how to sort them could come later.

**Comment by sparr** [comment]
Implemented by https://github.com/sparr/powercord-guild-list-order-shortcuts/commit/8b1d0259f800afb46793b0ee5f52c36f39c82fea

**Comment by sparr** [comment]
I didn't do member count because that's not available from the server list that's always present. Some other plugins keep a cache of member counts that update when you interact with the server, to avoid polling all the servers at once. If I try to add sorting by member count, I might copy that functionality, or I might add a dependency on one of them, or I might make that a separate plugin myself so others can depend on it and not duplicate effort.
